---

- name: Install package updates using Yum
  yum: name=* state=latest update_cache=yes
  when: ansible_pkg_mgr == "yum"

- name: Install package updates using Apt
  apt: upgrade=dist update_cache=yes
  when: ansible_pkg_mgr == "apt"
